pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
    stage('load') {
      steps {
       sh 'cat /proc/cpuinfo'
       sh 'cat /etc/os-release'
      }
    }
  }
}
